#ifndef __HARDWARE_SETTING_H__
#define __HARDWARE_SETTING_H__


#define FRONT_LEFT_JAGUAR_CANID  1
#define FRONT_RIGHT_JAGUAR_CANID 2
#define BACK_LEFT_JAGUAR_CANID   4
#define BACK_RIGHT_JAGUAR_CANID  3

#define SHOOTER_JAGUAR_CANID 31337

#define TOP_LIFT_JAGUAR_CANID 9001

#define BOTTOM_LIFT_LEFT_JAGUAR_CANID 666
#define BOTTOM_LIFT_RIGHT_JAGUAR_CANID 911

#define DRIVE_STICK_PORT 1


#endif
