#ifndef __HARDWARE_SETTING_H__
#define __HARDWARE_SETTING_H__


#define FRONT_LEFT_JAGUAR_CANID  1
#define FRONT_RIGHT_JAGUAR_CANID 2
#define BACK_LEFT_JAGUAR_CANID   4
#define BACK_RIGHT_JAGUAR_CANID  3

#define SHOOTER_JAGUAR_CANID 9
#define TENSIONER_JAGUAR_CANID 10

#define TOP_LIFT_JAGUAR_CANID 11

#define DRIVE_STICK_PORT 1
#define CAM_STICK_PORT 2

#define BALL_INTAKE_VICTOR_CHANNEL 1

#define BALL_LOADER_JAGUAR_CANID 10000

#define BOTTOM_LIFT_LEFT_SPIKE_RELAY_CHANNEL 2
#define BOTTOM_LIFT_RIGHT_SPIKE_RELAY_CHANNEL 3

#define SHOOTER_IR_SENSOR_PORT 121
#define LEFT_FRONT_IR_SENSOR_PORT 122
#define LEFT_BACK_IR_SENSOR_PORT 123
#define RIGHT_FRONT_IR_SENSOR_PORT 124
#define RIGHT_BACK_IR_SENSOR_PORT 125

#define GYRO_PORT 1

#endif
