#ifndef __HARDWARE_SETTING_H__
#define __HARDWARE_SETTING_H__


#define FRONT_LEFT_JAGUAR_CANID  1
#define FRONT_RIGHT_JAGUAR_CANID 2
#define BACK_LEFT_JAGUAR_CANID   4
#define BACK_RIGHT_JAGUAR_CANID  3

#define SHOOTER_JAGUAR_CANID 9
#define TENSIONER_JAGUAR_CANID 10

#define TOP_LIFT_JAGUAR_CANID 11

#define DRIVE_STICK_PORT 1
#define CAM_STICK_PORT 2

#define BALL_INTAKE_VICTOR_CHANNEL 1

#define BOTTOM_LIFT_LEFT_SPIKE_RELAY_CHANNEL 2
#define BOTTOM_LIFT_RIGHT_SPIKE_RELAY_CHANNEL 3

#define SHOOTER_IR_SENSOR_PORT 6
#define LEFT_FRONT_IR_SENSOR_PORT 5
#define LEFT_BACK_IR_SENSOR_PORT 3
#define RIGHT_FRONT_IR_SENSOR_PORT 4
#define RIGHT_BACK_IR_SENSOR_PORT 2

#define BALL_SENSOR_MODULE 5

#define INTAKE_BALL_SENSOR_CHANNEL 1
#define BOT_LIFT_BASE_BALL_SENSOR_CHANNEL 2
#define BOT_LIFT_MIDDLE_BALL_SENSOR_CHANNEL 3
#define TOP_LIFT_BALL_SENSOR_CHANNEL 4
#define SHOOTER_BALL_SENSOR_CHANNEL 5

#define GYRO_PORT 1

#define INCLUDE_BALL_CONTROL 1

#endif
